## Submitted by P S Vishwanath as
## Programming assignment 2 function for 
## caching the inverse of a matrix and using the cached result
## for repeat runs to save time. The solution consists of two
## functions: makeCacheMatrix and cacheSolve.
## The function makeCacheMatrix creates a special "matrix" object
## to save its inverse. The result of this function is a list of
## 4 functions: set, get, setinv and getinv.
## Uses R's lexical scoping with "<<-": e.g.,
## replaces x with y(input) from the main function in set.
makeCacheMatrix <- function(x = matrix()) { 
        inv <- NULL
        set <- function(y) { 
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinv <- function(solve) inv <<- solve
        getinv <- function() inv
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}
## This function checks if cached inv(x) exists [i.e., is not null].
## If yes, it returns the cached solution with a message and ends.
## If not, it gets the input matrix, calculates the inv(x) and 
## stores it in setinv in the object generated by makeCacheMatrix.
cacheSolve <- function(x, ...) {
        inv <- x$getinv()
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        mat.data <- x$get()
        inv <- solve(mat.data)
        x$setinv(inv)
        inv
}
## used the following to test out the function to verify it worked
## correctly.
## > x <- matrix(1:4, 2, 2)
## > z <- makeCacheMatrix(x)
## > cacheSolve(z)
